package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static cloud.autotests.helpers.DriverHelper.getConsoleLogs;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("Buy a bouquet of flowers")
    void generatedTest() {
        step("Открыть сайт 'https://flowers.ua'", () -> {
            // todo just add selenium action
        });

        step("В меню слева выбрать 'Цветы в коробке'", () -> {
            // todo just add selenium action
        });

        step("Найти предложение 'Цветы в коробке \"Гламур\"'", () -> {
            // todo just add selenium action
        });

        step("Нажать кнопку 'Заказать'", () -> {
            // todo just add selenium action
        });

        step("Ожидаемый результат: Наличие заказа на странице 'https://flowers.ua/ru/makeorder'", () -> {
            // todo just add selenium action
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...' and the page has 'title' tag")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://flowers.ua'", () ->
            open("https://flowers.ua"));

        step("Page title should have text 'Доставка цветов по Украине и миру. Купить цветы с доставкой. Интернет-магазин цветов Flowers.ua'", () -> {
            String expectedTitle = "Доставка цветов по Украине и миру. Купить цветы с доставкой. Интернет-магазин цветов Flowers.ua";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...'")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://flowers.ua'", () ->
            open("https://flowers.ua"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}